#version: '3.1'
#
#services:
#  master:
#    privileged: true
#    image: redis
#    container_name: redis-master
#    hostname: redis-master
#    #network_mode: host
#    command: redis-server /etc/redis/redis.conf
#    volumes:
#      - "/home/jiangtao/redis-test/sen/master/redis.conf:/etc/redis/redis.conf"
#    environment:
#      TZ: Asia/Shanghai
#    ports:
#      - "6379:6379"
#  slave_1:
#    privileged: true
#    image: redis
#    container_name: redis-slave_1
#    hostname: redis-slave_1
#    #network_mode: host
#    command: redis-server /etc/redis/redis.conf --slaveof redis-master 6379
#    volumes:
#      - "/home/jiangtao/redis-test/sen/slave1/redis.conf:/etc/redis/redis.conf"
#    environment:
#      TZ: Asia/Shanghai
#    links:
#      - master:redis-master
#    ports:
#      - "6380:6379"
#  slave_2:
#    privileged: true
#    image: redis
#    container_name: redis-slave_2
#    hostname: redis-slave_2
#    #network_mode: host
#    command: redis-server /etc/redis/redis.conf --slaveof redis-master 6379
#    volumes:
#      - "/home/jiangtao/redis-test/sen/slave2/redis.conf:/etc/redis/redis.conf"
#    environment:
#      TZ: Asia/Shanghai
#    links:
#      - master:redis-master
#    ports:
#      - "6381:6379"
#  sentinel_1:
#    privileged: true
#    image: redis
#    container_name: redis-sentinel_1
#    hostname: redis-sentinel_1
#    #network_mode: host
#    command: redis-sentinel /etc/redis/sentinel.conf --sentinel
#    volumes:
#      - "/home/jiangtao/redis-test/sen/sentinel1/sentinel.conf:/etc/redis/sentinel.conf"
#    environment:
#      TZ: Asia/Shanghai
#    links:
#      - master:redis-master
#      - slave_1
#      - slave_2
#    ports:
#      - "26379:26379"
#  sentinel_2:
#    privileged: true
#    image: redis
#    container_name: redis-sentinel_2
#    hostname: redis-sentinel_2
#    #network_mode: host
#    command: redis-sentinel /etc/redis/sentinel.conf --sentinel
#    volumes:
#      - "/home/jiangtao/redis-test/sen/sentinel2/sentinel.conf:/etc/redis/sentinel.conf"
#    environment:
#      TZ: Asia/Shangha
#    links:
#      - master:redis-master
#      - slave_1
#      - slave_2
#    ports:
#      - "26380:26379"
#  sentinel_3:
#    privileged: true
#    image: redis
#    container_name: redis-sentinel_3
#    hostname: redis-sentinel_3
#    #network_mode: host
#    command: redis-sentinel /etc/redis/sentinel.conf --sentinel
#    volumes:
#      - "/home/jiangtao/redis-test/sen/slave3/sentinel.conf:/etc/redis/sentinel.conf"
#    environment:
#      TZ: Asia/Shanghai
#    links:
#      - master:redis-master
#      - slave_1
#      - slave_2
#    ports:
#      - "26381:26379"
